name: CI

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        crystal:
          - "1.16"
          - "1.17"
          - "1.18"
          - "latest"

    container:
      image: crystallang/crystal:${{ matrix.crystal }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
